security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    encoders:
        App\Entity\User: bcrypt
        App\Entity\Company: bcrypt
        Symfony\Component\Security\Core\User\User: bcrypt
    providers:
        chain_provider:
            chain:
                providers: [in_memory, user_db, admin_db]
        in_memory:
            memory:
                users:
                    admin:
                        password: $2y$13$5WULBPImaF78C.a9Wltto.TDmmy20.nySlE0NyrJ48pyKh8ihvXze
                        roles: 'ROLE_SUPERADMIN'
        user_db:
            entity:
                class: App\Entity\Company
                property: email
        admin_db:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        superadmin_area:
            provider: in_memory
            http_basic: ~
            anonymous: ~
            pattern: ^/superadmin
            logout:
                path: main_logout
                target: admin_login
        admin_area:
            provider: admin_db
            http_basic: ~
            pattern: ^/admin
            anonymous: ~
            form_login:
                login_path: admin_login
                check_path: admin_login
                default_target_path: admin_index
            logout:
                path: admin_logout
                target: admin_login
        user_area:
            provider: user_db
            http_basic: ~
            pattern: ^/
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                default_target_path: client_index
            logout:
                path: logout
                target: login
        
            # activate different ways to authenticate

            # http_basic: true
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: true
            # https://symfony.com/doc/current/security/form_login_setup.html

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/superadmin, roles: ROLE_SUPERADMIN }
        - { path: ^/admin/*, roles: ROLE_ADMIN }
        - { path: ^/, roles: ROLE_USER }
    
    role_hierarchy:
        ROLE_SUPERADMIN: [ROLE_ADMIN, ROLE_SALES, ROLE_LOGISTIC]
        ROLE_SALES: [ROLE_ADMIN, ROLE_USER]
        ROLE_LOGISTIC: [ROLE_ADMIN, ROLE_USER]