# See https://symfony.com/doc/current/email/dev_environment.html
swiftmailer:
    # send all emails to a specific address
    #delivery_addresses: ['me@example.com']
    # url: gmail://oscar.eber@gmail.com:Argentina13!@localhost
    # spool: { type: 'memory' }